In [6]:
import pandas as pd
#from tabula import read_pdf

Collecting pdfminer.six
  Downloading pdfminer.six-20201018-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 3.2 MB/s eta 0:00:01
Requirement already satisfied: chardet in /home/natvalenz/dstools1/lib/python3.8/site-packages (from pdfminer.six) (4.0.0)
Collecting cryptography
  Downloading cryptography-3.4.6-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 19.4 MB/s eta 0:00:01
Requirement already satisfied: cffi>=1.12 in /home/natvalenz/dstools1/lib/python3.8/site-packages (from cryptography->pdfminer.six) (1.14.4)
Requirement already satisfied: pycparser in /home/natvalenz/dstools1/lib/python3.8/site-packages (from cffi>=1.12->cryptography->pdfminer.six) (2.20)
Collecting sortedcontainers
  Downloading sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, cryptography, pdfminer.six
Successfully installed cryptography-3.4.6 pdfminer.six-20201018 sortedcontainers-2.3.0
WARNING: You are using pip version 20.3.3; however, version 21.0.1 is available.
You should consider upgrading via the '/home/natvalenz/dstools1/bin/python3 -m pip install --upgrade pip' command.

In [35]:
#tb=read_pdf('nam_cost.pdf')
tables= pd.read_html('https://www.numbeo.com/cost-of-living/region_rankings.jsp?title=2020&region=021', header=0)
cost_living=tables[1]

Cost of Living Dataframe

In [37]:
def splitter(x, i):
    return x.split(',')[i]
cost_living=cost_living[cost_living.City.str.contains("United States")] 
cost_living.reset_index(drop=True, inplace=True)
cost_living["Rank"]=cost_living.index+1
cost_living["State"]=cost_living.City.apply(lambda x: splitter(x,1))
cost_living["Country"]=cost_living.City.apply(lambda x: splitter(x,2))
cost_living["City"]=cost_living.City.apply(lambda x: splitter(x,0))
cost_living.count()
cost_living

,Rank,City,Cost of Living Index,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,State,Country
0,1,New York,100.00,100.00,100.00,100.00,100.00,100.00,NY,United States
1,2,San Francisco,91.51,115.58,103.02,86.91,94.45,135.90,CA,United States
2,3,Anchorage,91.36,38.94,66.29,88.42,78.89,118.44,AK,United States
3,4,Honolulu,89.70,63.03,76.94,89.83,83.60,88.29,HI,United States
4,5,Brooklyn,88.82,80.49,84.84,83.22,92.77,92.95,NY,United States
5,6,Washington,87.74,78.18,83.17,86.44,87.48,130.25,DC,United States
6,7,Oakland,86.51,79.55,83.18,89.28,74.62,113.60,CA,United States
7,8,Seattle,85.77,65.70,76.17,81.69,81.25,133.43,WA,United States
8,9,Boston,82.88,74.47,78.86,81.23,81.85,112.39,MA,United States
9,10,Bellevue,82.18,63.24,73.12,76.86,76.62,163.27,WA,United States
10,11,Chicago,80.18,58.64,69.88,76.47,76.67,113.52,IL,United States
11,12,Sarasota,79.26,46.44,63.56,89.30,71.73,81.80,FL,United States
12,13,Philadelphia,78.84,46.87,63.55,77.46,72.85,100.23,PA,United States
13,14,San Jose,78.64,83.34,80.89,71.39,83.18,143.48,CA,United States
14,15,Portland,78.63,49.42,64.66,75.96,68.96,112.82,OR,United States
15,16,New Orleans,78.46,41.29,60.68,77.42,75.81,89.79,LA,United States
16,17,Sacramento,77.00,46.21,62.27,69.53,76.08,115.40,CA,United States
17,18,Minneapolis,76.70,45.26,61.66,67.93,78.55,127.18,MN,United States
18,19,Los Angeles,76.55,72.90,74.80,71.23,79.98,113.78,CA,United States
19,20,Albany,75.44,33.00,55.14,69.52,80.36,105.08,NY,United States
20,21,Jacksonville,74.57,33.58,54.97,76.90,78.78,120.90,FL,United States
21,22,Baltimore,74.29,42.61,59.14,67.97,76.71,125.24,MD,United States
22,23,San Diego,74.22,66.83,70.68,67.60,76.77,130.19,CA,United States
23,24,Miami,74.16,57.56,66.22,67.44,78.44,100.26,FL,United States
24,25,Buffalo,73.92,28.28,52.09,69.38,71.15,107.05,NY,United States
25,26,Atlanta,73.89,46.82,60.94,69.78,69.78,140.47,GA,United States
26,27,Reno,73.85,38.22,56.81,75.03,75.19,116.10,NV,United States
27,28,Pittsburgh,73.61,35.86,55.55,70.41,63.39,123.08,PA,United States
28,29,Denver,73.30,51.98,63.11,65.06,78.18,130.33,CO,United States
29,30,Nashville,73.19,46.76,60.55,65.28,80.79,122.67,TN,United States
30,31,Charlotte,72.40,42.37,58.04,62.17,79.73,144.29,NC,United States
31,32,Tucson,72.12,26.44,50.27,63.64,69.70,105.20,AZ,United States
32,33,Olympia,71.88,41.28,57.24,67.46,70.79,129.19,WA,United States
33,34,Colorado Springs,70.97,36.00,54.24,70.06,59.38,112.61,CO,United States
34,35,Tacoma,70.88,41.20,56.68,59.71,71.33,113.92,WA,United States
35,36,Saint Louis,70.78,28.97,50.79,70.32,64.46,126.33,MO,United States
36,37,Columbus,70.50,31.39,51.79,66.32,67.40,142.17,OH,United States
37,38,Raleigh,69.80,36.60,53.92,70.87,66.78,145.30,NC,United States
38,39,Kansas City,69.17,30.51,50.68,61.07,74.16,134.63,MO,United States
39,40,Dallas,68.03,47.05,58.00,60.90,70.47,155.30,TX,United States
40,41,Austin,67.79,52.04,60.26,63.85,72.03,145.76,TX,United States
41,42,Las Vegas,67.46,36.26,52.53,55.73,76.28,127.88,NV,United States
42,43,Phoenix,67.41,36.18,52.47,61.50,67.80,127.26,AZ,United States
43,44,Richmond,67.20,33.88,51.26,59.13,76.44,112.57,VA,United States
44,45,Tampa,67.10,40.83,54.53,64.79,63.51,126.19,FL,United States
45,46,Louisville,66.72,28.71,48.54,58.92,78.00,116.78,KY,United States
46,47,Indianapolis,66.34,29.25,48.60,61.97,62.59,110.02,IN,United States
47,48,San Antonio,65.78,36.50,51.77,62.69,64.86,116.40,TX,United States
48,49,Orlando,65.70,41.51,54.13,58.33,72.03,102.08,FL,United States
49,50,Houston,65.13,42.70,54.40,56.68,77.10,141.31,TX,United States
50,51,Salt Lake City,64.76,36.83,51.40,58.33,67.24,129.35,UT,United States
51,52,Madison,64.67,38.11,51.96,56.29,69.31,124.31,WI,United States
52,53,Tulsa,64.28,26.38,46.15,63.59,59.30,117.97,OK,United States
53,54,Detroit,63.85,37.80,51.39,63.33,58.91,78.58,MI,United States
54,55,Cincinnati,61.64,33.99,48.42,56.83,60.54,131.81,OH,United States
55,56,Boise,60.71,34.47,48.16,50.39,69.52,99.05,ID,United States
56,57,Little Rock,59.76,26.39,43.80,51.17,68.05,124.54,AR,United States
57,58,El Paso,52.38,22.71,38.19,52.57,39.93,127.67,TX,United States